### ISSUE TITLE
Error initforte

### ISSUE THREAD

**Issue by huuco** [evangelistalab/forte#26]
Hi developers,

I'm trying to install forte and running the tests but I encounter this error
```
Traceback (most recent call last):
  File "/temp0/tm/source/psi4-foss2017/bin/psi4", line 248, in <module>
    exec(content)
  File "<string>", line 20, in <module>

ImportError: dynamic module does not define init function (initforte)
```

Could you please help me solve this error?
To compile forte I used:
gcc version 6.3.0
python-2.7.13
the most recent psi4 from github, all the tests of psi4 passed
the most recent ambit from github

Thanks in advance

**Comment by jeffschriber** [comment]
Interesting. How did you compile Forte? Did you use the cmake_setup script, or did you manually do `psi4 --plugin-compile` and run cmake with the provided CMakeLists.txt?

**Comment by huuco** [comment]
I tried both cmake_setup and psi4 --plugin-compile.

**Comment by jeffschriber** [comment]
Try deleting all cmake files and folders, including CMakeLists.txt, and retry compiling with the cmake_setup script. Be sure to copy the whole cmake command that is printed (this seems to be missing from the instructions), it should look something like `cmake -C /usr/local/psi4/stage/usr/local/psi4/share/cmake/psi4/psi4PluginCache.cmake
  -DCMAKE_PREFIX_PATH=/usr/local/psi4/stage/usr/local/psi4 .` Once compiled, be sure that the forte.so file can be found in your PYTHONPATH.

**Comment by huuco** [comment]
I removed everything, clone again and recompiled. Still the same error.

```
$ python cmake_setup --psi4=/temp0/tm/source/psi4-foss2017/bin/psi4 --ambit-bindir=/temp0/tm/source/ambit-foss2017/
   root directory: /temp0/tm/source/forte
   psi4 executable: /temp0/tm/source/psi4-foss2017/bin/psi4
   ambit binary installation directory: /temp0/tm/source/ambit-foss2017/
   chemps2 binary installation directory: None

   is PSI4 compiled with MPI: False
   global arrays install directory: None


   configure step is done
   now you need to compile the sources:
   >>> cmake -C /temp0/tm/source/psi4-foss2017/share/cmake/psi4/psi4PluginCache.cmake -DCMAKE_PREFIX_PATH=/temp0/tm/source/psi4-foss2017 .

   >>> make

$ cmake -C /temp0/tm/source/psi4-foss2017/share/cmake/psi4/psi4PluginCache.cmake -DCMAKE_PREFIX_PATH=/temp0/tm/source/psi4-foss2017 .
loading initial cache file /temp0/tm/source/psi4-foss2017/share/cmake/psi4/psi4PluginCache.cmake
-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /temp0/tm/gcc-6.3/bin/g++
-- Check for working CXX compiler: /temp0/tm/gcc-6.3/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Psi4 script:  /temp0/tm/source/psi4-foss2017/bin/psi4
-- Psi4 headers: /temp0/tm/source/psi4-foss2017/include
-- Psi4 library: /temp0/tm/source/psi4-foss2017/lib//psi4/core.so
-- Psi4 components: ambit;chemps2;dkh;pcmsolver
-- Python executable: /temp0/tm/python-2.7-foss2017/bin/python
-- Found PythonInterp: /temp0/tm/python-2.7-foss2017/bin/python (found version "2.7.13") 
-- Found PythonLibs: /temp0/tm/python-2.7-foss2017/lib/libpython2.7.a
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /temp0/tm/source/forte

$ make
Scanning dependencies of target forte
[  1%] Building CXX object CMakeFiles/forte.dir/src/active_dsrgpt2.cc.o
[  2%] Building CXX object CMakeFiles/forte.dir/src/ao_helper.cc.o
[  3%] Building CXX object CMakeFiles/forte.dir/src/avas.cc.o
[  4%] Building CXX object CMakeFiles/forte.dir/src/bitset_performance.cc.o
[  5%] Building CXX object CMakeFiles/forte.dir/src/blockedtensorfactory.cc.o
[  6%] Building CXX object CMakeFiles/forte.dir/src/casscf.cc.o
[  7%] Building CXX object CMakeFiles/forte.dir/src/cc.cc.o
[  8%] Building CXX object CMakeFiles/forte.dir/src/ci_rdms.cc.o
[  9%] Building CXX object CMakeFiles/forte.dir/src/ci_reference.cc.o
[ 10%] Building CXX object CMakeFiles/forte.dir/src/davidson.cc.o
[ 11%] Building CXX object CMakeFiles/forte.dir/src/determinant_map.cc.o
[ 12%] Building CXX object CMakeFiles/forte.dir/src/dmrgscf.cc.o
[ 13%] Building CXX object CMakeFiles/forte.dir/src/dmrgsolver.cc.o
[ 14%] Building CXX object CMakeFiles/forte.dir/src/dynamic_bitset_determinant.cc.o
...
[ 92%] Building CXX object CMakeFiles/forte.dir/src/mrdsrg-spin-free/three_dsrg_mrpt2.cc.o
[ 93%] Building CXX object CMakeFiles/forte.dir/src/orbital-helper/localize.cc.o
[ 94%] Building CXX object CMakeFiles/forte.dir/src/orbital-helper/unpaired_density.cc.o
[ 95%] Building CXX object CMakeFiles/forte.dir/src/pci/ewci.cc.o
[ 96%] Building CXX object CMakeFiles/forte.dir/src/pci/pci.cc.o
[ 97%] Building CXX object CMakeFiles/forte.dir/src/pci/pci_hashvec.cc.o
[ 98%] Building CXX object CMakeFiles/forte.dir/src/pci/pci_simple.cc.o
[100%] Linking CXX shared module forte.so
[100%] Built target forte

$ export PYTHONPATH=/temp0/tm/source/forte:$PYTHONPATH

```

**Comment by fevangelista** [comment]
I think the issue is `export PYTHONPATH=/temp0/tm/source/forte:$PYTHONPATH`. Can you try `export PYTHONPATH=/temp0/tm/source:$PYTHONPATH` instead?

**Comment by huuco** [comment]
Yes, it's fixed.
Sorry for my stupid mistake.
Thanks.

**Comment by fevangelista** [comment]
No problem! I ran into the same problem just a few weeks ago.
