### ISSUE TITLE
forte error

### ISSUE THREAD

**Issue by chburger** [evangelistalab/forte#282]
I see an error when I import forte.

firefly:~/src/forte/forte> python3
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psi4
>>> import forte
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/burger/src/forte/forte/__init__.py", line 61, in <module>
    forte_options.push_options_to_psi4(psi_options)
TypeError: push_options_to_psi4(): incompatible function arguments. The following argument types are supported:
    1. (self: forte._forte.ForteOptions, arg0: psi::Options) -> None

**Comment by JonathonMisiewicz** [comment]
Thanks for the report. I ran into this issue today myself. To fix this reliably, you need to install ambit and Psi4 from scratch.

This is a limitation of the pybind dependency and not something we can fix, sadly: https://github.com/pybind/pybind11/issues/3793
